# Site settings
title: Rchard2scout's Personal Site
email: rchard2scout@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my personal website. I'm testing out Jekyll.
  More things are to come. Some time.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rchard2scout.github.io" # the base hostname & protocol for your site
twitter_username: rchard2scout
github_username:  rchard2scout

# Build settings
markdown: kramdown
